### ISSUE TITLE
Pdb still locks

### ISSUE THREAD

**Issue by septag** [fungos/cr#12]
Hi,
I was testing out your library and noticed that on visual studio 2015 (update 3) it still locks the original pdb.
I have checked cr_pdb_replace function to see if the pdb name is replaced and it does, but after cr_so_load, the original pdb is locked instead of versioned one.
does visual studio gets it's pdb path from somewhere else instead of binary ?

**Comment by fungos** [comment]
Thanks for the link, that is interesting and remembers me that I have some more things to write in the troubleshooting section, I'll take the time and add this info there too.
