### ISSUE TITLE
multiple definition issue

### ISSUE THREAD

**Issue by alexxbb** [fungos/cr#55]
Hi. Thank you for this project, it's exactly what I was looking for, however  I'm stuck with the linker errors:

`multiple definition of cr_plugin_open; CMakeFiles/hrust_sop.dir/plugin_manager.cpp.o`
.... same for all other **cr_plugin_*** symbols

What I can figure out is how **cr.h** is getting into all of my compilation units. 

I should say that I include **cr.h** into my header, which is then gets included in a few other places (with guards).
I suspect **cr.h** can not be included into headers, but instead should be only used in a cpp file?

I will appreciate any help,

Alex

**Comment by fungos** [comment]
Sorry, I didn't see this one. Yes, you shouldn't include cr.h in header files. Keep it in only one c/cpp file or put ifdef guards if you really need it.
