### ISSUE TITLE
Assert protection?

### ISSUE THREAD

**Issue by clibequilibrium** [fungos/cr#66]
Hey, I hope this message finds you well.

Is there a possibility to add assert protection? I was looking at `cr_signal_to_failure `and `sigsetjmp`

For instance when imgui throws something like 
`Assertion failed: (g.WithinEndChild) && "Must call EndChild() and not End()!", file imgui.cpp, line 7162 ` currently my .dll just crashes and isn't rolling back as it's not considering it as a seg fault or anything like that . 

I am on windows, gcc + mingw32

**Comment by fungos** [comment]
Hello! In linux an assert would emit an abort which would translate to a sigabrt which should be handled by cr. I'm not sure what mingw32 does here, but I would expect it to be compatible with linux.
In resume, assert should be handled, if it is not working then it is something to fix. I'll need time to investigate all situations, but I don't have an easy mingw32 setup ready. If you want to contribute a fix, it would be awesome otherwise I can't promise any timeline on this.

**Comment by clibequilibrium** [comment]
> Hello! In linux an assert would emit an abort which would translate to a sigabrt which should be handled by cr. I'm not sure what mingw32 does here, but I would expect it to be compatible with linux. In resume, assert should be handled, if it is not working then it is something to fix. I'll need time to investigate all situations, but I don't have an easy mingw32 setup ready. If you want to contribute a fix, it would be awesome otherwise I can't promise any timeline on this.

Thank you for your reply. I will try on Ubuntu to see if that's the case and see what I can do for mingw32. Once I find anything I will try to make a solution and have a PR ready. Thank you 🙌

**Comment by fungos** [comment]
See: https://docs.microsoft.com/en-us/previous-versions/k089yyh0(v=vs.140)?redirectedfrom=MSDN
You can try putting an `abort()` somewhere and debugging what happens on signal handler side, but following this doc, it should be the same expected behavior.

**Comment by clibequilibrium** [comment]
Okay I think because the assert is thrown from a 3rd party library which is statically linked to my core library the assert protection is not working.  Could that be the reason. 

I have core library (is statically linked to imgui) which is not hot reloadable and application that dynamically links to the core library. When I change something on application side related to imgui and this causes assert on host side maybe?

**Comment by clibequilibrium** [comment]
Could you please take a look at this PR when you have time? @fungos 
I also have question is that okay to return -1 in the try catch block ?

Thank you

https://github.com/fungos/cr/pull/67

**Comment by clibequilibrium** [comment]
I also think I will explore your sigsetjmp and longjmp under MingW32 to see if I can properly support everything.

**Comment by clibequilibrium** [comment]
I see longjmp and setjmp fails from time to time. I am not sure if my PR is stable enough to be merged. 
https://web.archive.org/web/20210625044548/http://www.agardner.me/golang/windows/cgo/64-bit/setjmp/longjmp/2016/02/29/go-windows-setjmp-x86.html

I found some clues as well

**Comment by fungos** [comment]
Hi @clibequilibrium , sorry about the delay. Great to know that you found the issue and fixed it yourself, this is awesome!
I put some comments on the PR, just details. Overall it looks good to me.

Can you also take the time and add your name to the contributors list in the top comment/documentation in the file before merging the PR?

Thanks again for contributing!

**Comment by clibequilibrium** [comment]
Will do @fungos  !

**Comment by fungos** [comment]
Fixed by #67
