### ISSUE TITLE
No error when cr_main is missing

### ISSUE THREAD

**Issue by rokups** [fungos/cr#7]
I am fairly confident this is a bug, but wanted to double-check.

In case loadable module does not have `cr_main` exported `cr_plugin_update()` does not report an error. What happens is host is trying to load guest over and over spamming console with errors and doing nothing. Shouldnt `cr_plugin_update()` return an error in this case?

**Comment by fungos** [comment]
I would consider this an CR_USER error. Maybe the right thing to do here is to fix this to return -1  https://github.com/fungos/cr/blob/b234eee3f743478cd0d9fd5f288b4c44456a9c02/cr.h#L1281
